### PR TITLE
Add 'display player frame' option

### PR DESCRIPTION
**Pull request by BannZay**
Addon duplicates information about player. There was no solution to  this problem apart from hiding player frame (what I personally dislike)

This PR enables possibility to hide player information

изображение
изображение

### CODE REVIEW

**Comment by BannZay** [comment]
This ability is very useful on arena

**Comment by BannZay** [comment]
The only problem I faced is that new option is not checked off after migration (if old savedvariables used with this version).

But I believe that this is rather general addon problem... or I did something wrong.

**Comment by RomanSpector** [comment]
I'm not sure it's worth adding this. My goal was to export from retail without any changes or additions.

Perhaps this should be done as a separate addon, then I could add it to my discord channel and provide links to authorshipI'm not sure it's worth adding this. My goal was to export from retail without any changes or additions.

Perhaps this should be done as a separate addon, then I could add it to my discord channel and provide links to authorship

**Comment by BannZay** [comment]
I see.

More and more people going to use it and they liked it pretty much (including me). 

You could do a branch or separete repository for aggregating improvements. This way there will be a single place to pull updates and share feedback. What is great.

But I can do separate repo by myself if you dont like to own and maintain it.

Anyway, I want to say thank you for this beauty addon backport :)

**Comment by BannZay** [comment]
Let me know if you gona do this so I will make new PR.

P.s.: You can also find me on your discord channel

**Pull request closed without merging**
